### ISSUE TITLE
Blockchain list

### ISSUE THREAD

**Issue by Syr3mas** [input-output-hk/cardano-byron-cli#30]
Main blockchain NodeM7 isn't showing when calling 'list':

RUST_BACKTRACE=1 /cardano-cli blockchain list
testnet-1
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing:: imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: cardano_cli::blockchain::Blockchain::load
  10: cardano_cli::blockchain::commands::list
  11: cardano_cli::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  16: main
  17: __libc_start_main
  18: _start
             at ../sysdeps/x86_64/start.S:120

Should of have a 'NodeM7' blockchain copy showing up but nothing.
- When I use 'status' all the info is shown
- The wallet attached to the NodeM7 blockchain is present with everything
- Using 'log' list all the blocks of NodeM7 blockchain
Then I tried this:
- /cardano-cli blockchain new nodeM7:   local blockchain `nodeM7' created.
- /cardano-cli blockchain list
   testnet-1
   thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
I did play around with 'remote-add' and 'remote-rm' a couple of times for peer connection purposes.

**Comment by Syr3mas** [comment]
Appropriate fix to resolve the issue. #31
